add logger files
DenOn79/Hillel_QA_Automation_Homeworks_NEW pull request #3
Opened 2021-11-29 19:47 UTC by DenOn79

2021-11-29 19:54 UTC, apollyonix requested changes
Технически всё верно, только не хватает маленькой логической делали - логируемого сообщения, которое передаётся логгеру в качестве параметра

2021-11-29 19:54 UTC, apollyonix commented on src/logger/Logger.java
> +    public static void setLevels(LogLevels levels) {
задача логгера - что-то вывести в лог)) не мешало бы тут ещё добавить это "что-то", то сообщение, которое мы хотим залогировать

2021-11-30 05:44 UTC, DenOn79 commented on src/logger/Logger.java
> +    public static void setLevels(LogLevels levels) {
Понял, спасибо большое!) если честно, то не сразу понял из условия задачи, какая именно функциональность должна быть)) теперь уяснил. для пущей схожести с настоящим логированием добавил еще текущую дату в лог

2021-11-30 07:29 UTC, apollyonix approved these changes
Отлично)

2021-11-30 07:29 UTC, apollyonix commented on src/logger/CurrentDate.java
> +public class CurrentDate {
Можно сразу в методе логгера получать текущую дату, не обязательно для этого создавать целый отдельный класс)

2021-11-30 07:30 UTC, merged